### ISSUE TITLE
Docker Container yamux deadline

### ISSUE THREAD

**Issue by robbycuenot** [hashicorp/terraform-docs-agents#81]
I'm not able to see the repo for the agent itself, so I am dropping the issue here.

I am running the agent using synology container manager. Once per day, around 1:30 AM Eastern Time, the container fails with the following logs:

```
2023/10/24 01:30:57,stdout,Graceful shutdown complete
2023/10/24 01:30:57,stdout,2023-10-24T05:30:56.411Z [WARN]  plugin: plugin failed to exit gracefully
2023/10/24 01:30:57,stdout,2023-10-24T05:30:56.411Z [WARN]  plugin: error closing client during Kill: err="connection is shut down"
2023/10/24 01:30:57,stdout,2023-10-24T05:30:56.411Z [INFO]  agent: Core plugin is shutting down
2023/10/24 01:30:57,stdout,2023-10-24T05:30:56.411Z [INFO]  agent: Shutting down
2023/10/24 01:30:57,stdout,2023-10-24T05:30:56.410Z [ERROR] agent: Failed checking core for errors: error="connection is shut down"
2023/10/24 01:30:54,stdout,2023-10-24T05:30:45.817Z [ERROR] agent: Failed handling job: error="unexpected EOF"
2023/10/24 01:30:47,stdout,2023/10/24 05:30:45 [ERR] yamux: keepalive failed: i/o deadline reached
2023/10/24 00:34:48,stdout,2023-10-24T04:34:48.268Z [INFO]  agent: Core version is up to date: version=1.13.0
2023/10/23 23:29:55,stdout,2023-10-24T03:29:55.804Z [INFO]  agent: Core version is up to date: version=1.13.0
2023/10/23 22:29:48,stdout,2023-10-24T02:29:47.749Z [INFO]  agent: Core version is up to date: version=1.13.0
2023/10/23 21:27:53,stdout,2023-10-24T01:27:53.249Z [INFO]  agent: Core version is up to date: version=1.13.0
```

I am guessing it is due to the `yamux: keepalive failed: i/o deadline reached` line. Yamux is managed by hashicorp and I know handles multiplexing for the container. Are there additional settings I should be specifying to prevent the container from dying every 24 hours?

**Comment by ggambetti** [comment]
Unfortunately the error itself isn't sufficient to determine what's going on.

The Agents usage of [yamux](https://github.com/hashicorp/yamux) comes from [go-plugin](https://github.com/hashicorp/go-plugin). Both repositories have seen numerous bug fixes in the ~year since you filed this report. Some of which are related to deadlines/timeouts/concurrency, which is possibly what you've observed.

I'm going to close this in the hope that upgrading from `1.13` to something more recent has addressed the issue.
